#!/bin/bash

if [ -z "$1" ]; then
	echo "No arguments provided!"
	exit 1
fi

mkdir $1
cd $1
cp ../README.md .
cp ../commit .
mkdir ilahe
cd ilahe
git clone https://github.com/ilaahe04/holbertonschool-web_front_end
cd holbertonschool-web_front_end
cd $1
mv * ../../../
cd ../../../
rm -rf ilahe
./commit
